### ISSUE TITLE
Upgrade bit.ly links for FEHN on Meetup.com

### ISSUE THREAD

**Issue by alulsh** [wgxcodersdc/front-end-community#1]
/cc @kdmcclin @womenwhocodedc/front-end-leads @pamtaro @nupurkapoor 

Many of the front end resources in [/organization](https://github.com/womenwhocodedc/organization) are tied to bit.ly short links listed on the [Meetup page for Front End Hack Night](http://www.meetup.com/Women-Who-Code-DC/events/228165106/).

After we have moved the docs to [/front-end-community](https://github.com/womenwhocodedc/front-end-community), we should first log in to bit.ly and then update the short links before removing the front end docs from [/organization](https://github.com/womenwhocodedc/organization).

Next Steps
- [x] Move front end docs from /organization to /front-end-community (done by @kdmcclin in https://github.com/womenwhocodedc/front-end-community/pull/2 because she's _awesome_)
- [x] Obtain login to bit.ly from WWCDC leadership (do not post credentials on Github)
- [x] Move study guides to dedicated folder per https://github.com/womenwhocodedc/front-end-community/issues/5
- [x] Create new bit.ly URL for http://bit.ly/frontendhacknight
- [x] Create new bit.ly URL for http://bit.ly/first-timers-guide
- [x] Create new bit.ly URL for http://bit.ly/html-study-guide
- [x] Create new bit.ly URL for http://bit.ly/js-study-guide
- [x] Update meetup page with new bit.ly URLs

**Comment by nupurkapoor** [comment]
Awesome!!!! Thanks Alex :)

**Comment by alulsh** [comment]
Ah, sadly you cannot update existing bit.ly links on free plans per the bit.ly docs (http://support.bitly.com/customer/portal/articles/1842459?b_id=5611).

We should instead create new bit.ly links after implementing https://github.com/womenwhocodedc/front-end-community/issues/5. The bit.ly links should be created using the WWCDC account to avoid being tied to a member's personal account.

Original issue comment has been updated with new steps.

**Comment by alulsh** [comment]
Per chat with @mmlumba in the WWCDC Slack, she's going to take this on!

**Comment by mmlumba** [comment]
Change reflected in pull request #11
