### ISSUE TITLE
Create onboarding checklist

### ISSUE THREAD

**Issue by alulsh** [wgxcodersdc/front-end-community#18]
We need to transfer the Front End onboarding checklist from Google Drive to a markdown file.

/cc @womenwhocodedc/front-end-leads @mmlumba

**Comment by mmlumba** [comment]
PR #21 for reference

**Comment by mmlumba** [comment]
Approved and merged

**Comment by alulsh** [comment]
Looks great @mmlumba! Nice work :clap: :clap:
