### ISSUE TITLE
Typo in first_timers_javascript_guide.md

### ISSUE THREAD

**Issue by ncclementi** [wgxcodersdc/front-end-community#27]
Hello there, I've just found a typo in the `first_timers_javascript_guide.md`

In the Variables section, we have:

`var myAge = 18;`

and then we have

`var oldAge = myage + 100;`

which should be:

`var oldAge = myAge + 100`

It's a small change that's why I didn't open a pull request. I think someone with push access can fix it faster. ;)

**Comment by kdmcclin** [comment]
Thanks! Sorry it took so long to notice. It should be fixed now.
